### ISSUE TITLE
Order image list by name not lexicographically

### ISSUE THREAD

**Issue by MikeGillotti** [MikeGillotti/chronoref#3]
For example (image1, image5, image10) instead of (image1, image10, image5)

**Comment by Abh1noob** [comment]
are you going to provide the file location and then you want to sort it by name then display accordingly? or you are getting (image1, image10, image5) somewhere in code but you are expecting (image1, image5, image10) . if the case is latter, share reference line number, I may try to help you out, else, i'll code for former on your confirmation.

**Comment by Abh1noob** [comment]
ok, I tried, actually for me, by default i am getting in  (image1, image5, image10 format
