### ISSUE TITLE
Add leading zeros to minutes and seconds in timer.

### ISSUE THREAD

**Issue by MikeGillotti** [MikeGillotti/chronoref#8]
For example, if the timer had 3 minutes and 2 seconds left, it should display 03:02 instead of 3:2.

**Comment by skanderboudawara** [comment]
Hello can you assign this to me ?

**Comment by MikeGillotti** [comment]
> Hello can you assign this to me ?

Done :)

**Comment by skanderboudawara** [comment]
PR done,

 I did some code formatting using Blake :D for better readability
